#!/usr/bin/env python3
"""Nestling's logo: a bird resting on a nest of three flat bars.

Writes, from one set of shapes on the 108 x 108 adaptive-icon canvas:
  - the Android adaptive launcher icon (Android 8+): background color, colored foreground and a
    monochrome layer for Android 13+ themed icons (vector drawables under android/.../res),
  - SVG masters in assets/brand/: logo.svg (full-bleed square, for maskable/store icons),
    logo-round.svg (round, transparent corners) and logo-mono.svg (one color).

Run from app/:  python3 tool/android_icon.py
The PNGs (web/icons, web/favicon.png, assets/icon.png, android mipmap-*/ic_launcher.png for
Android < 8) are rendered from the SVG masters at their sizes.
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(HERE, "..", "android", "app", "src", "main", "res")
BRAND = os.path.join(HERE, "..", "assets", "brand")

BACKGROUND = "#3D7A6A"  # eucalyptus (the app's accent)
BIRD = "#F0A06A"  # apricot
BEAK = "#F4D48E"  # honey
NEST = "#F7F3EC"  # oat

# Launchers show the middle 72 dp and keep the middle 66 dp safe from any mask; SCALE leaves
# some breathing room around the drawing.
SCALE = 0.92


def circle(cx, cy, r):
    return f"M{cx - r},{cy} A{r},{r} 0 1,1 {cx + r},{cy} A{r},{r} 0 1,1 {cx - r},{cy} Z"


def dome(cx, cy, r, cut):
    """A circle with its bottom cut off flat at height `cut`."""
    dx = (r * r - (cut - cy) ** 2) ** 0.5
    return f"M{cx - dx:.2f},{cut} A{r},{r} 0 1,1 {cx + dx:.2f},{cut} Z"


def bar(x0, y0, x1, y1):
    """Rounded bar (pill)."""
    r = (y1 - y0) / 2
    return f"M{x0 + r},{y0} H{x1 - r} A{r},{r} 0 0 1 {x1 - r},{y1} H{x0 + r} A{r},{r} 0 0 1 {x0 + r},{y0} Z"


# The bird: a dome sitting just above the nest, an eye cut out of it, and a beak.
BODY = dome(52, 47.5, 15.5, 56.0)
EYE = circle(57.8, 42.6, 2.3)
BEAK_PATH = "M65.6,43.2 L74.2,47.4 L65.9,51.6 Z"
# The nest: three bars, each narrower, with the same gap as between bird and nest.
BAR_H, BAR_GAP, TOP = 4.6, 2.6, 58.6
BARS = [
    bar(x0, TOP + i * (BAR_H + BAR_GAP), x1, TOP + i * (BAR_H + BAR_GAP) + BAR_H)
    for i, (x0, x1) in enumerate([(29, 79), (34, 74), (41, 67)])
]


def layers(bird, beak, nest):
    """(pathData, color, evenOdd) for the drawing; the eye is a hole in the body."""
    return [(BODY + " " + EYE, bird, True), (BEAK_PATH, beak, False)] + [(b, nest, False) for b in BARS]


FOREGROUND = layers(BIRD, BEAK, NEST)
MONOCHROME = layers("#FFFFFFFF", "#FFFFFFFF", "#FFFFFFFF")  # the launcher tints it


def vector(paths):
    out = [
        '<?xml version="1.0" encoding="utf-8"?>',
        "<!-- Generated by tool/android_icon.py; edit the script, not this file. -->",
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
        '    android:width="108dp" android:height="108dp"',
        '    android:viewportWidth="108" android:viewportHeight="108">',
        f'  <group android:pivotX="54" android:pivotY="54" android:scaleX="{SCALE}" android:scaleY="{SCALE}">',
    ]
    for data, color, even_odd in paths:
        fill = ' android:fillType="evenOdd"' if even_odd else ""
        out.append(f'    <path android:pathData="{data}" android:fillColor="{color}"{fill} />')
    out += ["  </group>", "</vector>"]
    return "\n".join(out) + "\n"


def svg(paths, background=None, round_=False):
    """SVG master. Round: the launcher's visible middle (72 of 108) in a circle."""
    view = "18 18 72 72" if round_ else "0 0 108 108"
    out = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{view}">']
    if background and round_:
        out.append(f'<circle cx="54" cy="54" r="36" fill="{background}"/>')
    elif background:
        out.append(f'<rect width="108" height="108" fill="{background}"/>')
    out.append(f'<g transform="translate(54 54) scale({SCALE}) translate(-54 -54)">')
    for data, color, even_odd in paths:
        rule = ' fill-rule="evenodd"' if even_odd else ""
        out.append(f'<path d="{data}" fill="{color[:7]}"{rule}/>')
    out.append("</g></svg>")
    return "\n".join(out) + "\n"


ADAPTIVE = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/android_icon.py. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>
"""

COLORS = f"""<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="ic_launcher_background">{BACKGROUND}</color>
</resources>
"""


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(text)
    print("wrote", os.path.relpath(path))


def main():
    write(os.path.join(RES, "drawable/ic_launcher_foreground.xml"), vector(FOREGROUND))
    write(os.path.join(RES, "drawable/ic_launcher_monochrome.xml"), vector(MONOCHROME))
    write(os.path.join(RES, "mipmap-anydpi-v26/ic_launcher.xml"), ADAPTIVE)
    write(os.path.join(RES, "values/ic_launcher_background.xml"), COLORS)
    write(os.path.join(BRAND, "logo.svg"), svg(FOREGROUND, BACKGROUND))
    write(os.path.join(BRAND, "logo-round.svg"), svg(FOREGROUND, BACKGROUND, round_=True))
    write(os.path.join(BRAND, "logo-mono.svg"), svg([(d, "#3D7A6A", e) for d, _, e in MONOCHROME]))


if __name__ == "__main__":
    main()
