#!/usr/bin/env python3
"""Writes the Android adaptive launcher icon (Android 8+) as vector drawables.

Layers on the 108 x 108 dp adaptive-icon canvas (launchers show the middle ~72 dp and keep
the middle 66 dp safe from any mask shape):
  - background: the sage green,
  - foreground: the bird in its nest, in color,
  - monochrome: the same drawing in one color (Android 13+ "themed icons" tint it).

Run from app/:  python3 tool/android_icon.py   (or with --svg DIR to also write SVG previews)
The legacy PNGs in mipmap-*/ic_launcher.png stay for older Android versions.
"""

import os
import sys

RES = os.path.join(os.path.dirname(__file__), "..", "android", "app", "src", "main", "res")

SAGE = "#CADFBC"
BODY = "#D9824E"
EYE = "#2E2925"
BEAK = "#EBC46E"
NEST = "#7A5F3C"
TWIG = "#B89A72"

# The drawing, centered in the safe zone (all in dp on the 108 canvas).
BODY_CIRCLE = (54, 51, 17)  # cx, cy, r
EYE_CIRCLE = (60.1, 46.4, 2.4)
BEAK_PATH = "M69.5,50.1 L79.2,53.1 L69.5,56.2 Z"
NEST_PATH = "M28,58.8 L80,58.8 C76,66 66,71.8 54,71.8 C42,71.8 32,66 28,58.8 Z"
TWIG_PATHS = ["M31,61.6 Q54,80.2 77,61.6", "M34.9,66.6 Q54,81.8 73.1,66.6"]
TWIG_WIDTH = 2.2
# Shrink the drawing around the center for breathing room inside the launcher's mask.
SCALE = 0.9


def circle(cx, cy, r):
    return f"M{cx - r},{cy} A{r},{r} 0 1,1 {cx + r},{cy} A{r},{r} 0 1,1 {cx - r},{cy} Z"


def body_above(y):
    """The bird's body cut at height y, leaving a gap above the nest (monochrome)."""
    cx, cy, r = BODY_CIRCLE
    dx = (r * r - (y - cy) ** 2) ** 0.5
    return f"M{cx - dx:.2f},{y} A{r},{r} 0 1,1 {cx + dx:.2f},{y} Z"


def vector(paths):
    """paths: list of (pathData, fill, stroke, strokeWidth, evenOdd)."""
    out = [
        '<?xml version="1.0" encoding="utf-8"?>',
        "<!-- Generated by tool/android_icon.py; edit the script, not this file. -->",
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
        '    android:width="108dp" android:height="108dp"',
        '    android:viewportWidth="108" android:viewportHeight="108">',
        f'  <group android:pivotX="54" android:pivotY="54" android:scaleX="{SCALE}" android:scaleY="{SCALE}">',
    ]
    for data, fill, stroke, width, even_odd in paths:
        attrs = [f'android:pathData="{data}"']
        if fill:
            attrs.append(f'android:fillColor="{fill}"')
        if stroke:
            attrs += [f'android:strokeColor="{stroke}"', f'android:strokeWidth="{width}"', 'android:strokeLineCap="round"']
        if even_odd:
            attrs.append('android:fillType="evenOdd"')
        out.append("    <path " + " ".join(attrs) + " />")
    out.append("  </group>")
    out.append("</vector>")
    return "\n".join(out) + "\n"


def svg(paths, background=None):
    out = ['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 108 108" width="432" height="432">']
    if background:
        out.append(f'<rect width="108" height="108" fill="{background}"/>')
    out.append(f'<g transform="translate(54 54) scale({SCALE}) translate(-54 -54)">')
    for data, fill, stroke, width, even_odd in paths:
        attrs = f'd="{data}" fill="{fill or "none"}"'
        if stroke:
            attrs += f' stroke="{stroke}" stroke-width="{width}" stroke-linecap="round"'
        if even_odd:
            attrs += ' fill-rule="evenodd"'
        out.append(f"<path {attrs}/>")
    out.append("</g></svg>")
    return "\n".join(out)


FOREGROUND = [
    (circle(*BODY_CIRCLE), BODY, None, 0, False),
    (circle(*EYE_CIRCLE), EYE, None, 0, False),
    (BEAK_PATH, BEAK, None, 0, False),
    (NEST_PATH, NEST, None, 0, False),
    *[(p, None, TWIG, TWIG_WIDTH, False) for p in TWIG_PATHS],
]

# One color; the launcher tints it. The eye is a hole, the bird floats just above the nest,
# and only the lower twig shows (it hangs below the bowl).
MONO = "#FFFFFFFF"
MONOCHROME = [
    (body_above(57.4) + " " + circle(*EYE_CIRCLE), MONO, None, 0, True),
    (BEAK_PATH, MONO, None, 0, False),
    (NEST_PATH, MONO, None, 0, False),
    (TWIG_PATHS[1], None, MONO, TWIG_WIDTH, False),
]

ADAPTIVE = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/android_icon.py. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>
"""

COLORS = f"""<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="ic_launcher_background">{SAGE}</color>
</resources>
"""


def write(rel, text):
    path = os.path.join(RES, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(text)
    print("wrote", os.path.relpath(path))


def main():
    write("drawable/ic_launcher_foreground.xml", vector(FOREGROUND))
    write("drawable/ic_launcher_monochrome.xml", vector(MONOCHROME))
    write("mipmap-anydpi-v26/ic_launcher.xml", ADAPTIVE)
    write("values/ic_launcher_background.xml", COLORS)
    if "--svg" in sys.argv:
        out = sys.argv[sys.argv.index("--svg") + 1]
        os.makedirs(out, exist_ok=True)
        with open(os.path.join(out, "color.svg"), "w") as f:
            f.write(svg(FOREGROUND, SAGE))
        with open(os.path.join(out, "mono.svg"), "w") as f:
            f.write(svg(MONOCHROME))
        print("previews in", out)


if __name__ == "__main__":
    main()
