#!/usr/bin/env python3
"""Generates lib/growth/who_lms.dart from the WHO Child Growth Standards tables.

The WHO publishes, for each sex and age, the L, M and S parameters of weight-for-age,
length-for-age and head-circumference-for-age (https://www.who.int/tools/child-growth-standards).
This reads the same tables as distributed in the `pygrowup` package (BSD; tables under the WHO
license) and keeps weekly values to 13 weeks, then monthly ones to 24 months.

Usage (from app/):  pip download --no-deps --no-binary :all: pygrowup && tar xzf pygrowup-*.tar.gz
                    python3 tool/who_tables.py pygrowup-*/pygrowup/tables
"""

import json
import os
import sys

DAYS_PER_MONTH = 365.25 / 12
INDICATORS = {"weight": "wfa", "length": "lhfa", "head": "hcfa"}
MONTHLY = {"wfa": "0_5", "lhfa": "0_2", "hcfa": "0_5"}


def rows(src, prefix, sex):
    weekly = json.load(open(os.path.join(src, f"{prefix}_{sex}_0_13_zscores.json")))
    monthly = json.load(open(os.path.join(src, f"{prefix}_{sex}_{MONTHLY[prefix]}_zscores.json")))
    out = [(int(r["Week"]) * 7, float(r["L"]), float(r["M"]), float(r["S"])) for r in weekly]
    last = out[-1][0]
    for r in monthly:
        day = int(r["Month"]) * DAYS_PER_MONTH
        if last < day <= 24 * DAYS_PER_MONTH + 0.01:
            out.append((round(day, 2), float(r["L"]), float(r["M"]), float(r["S"])))
    return out


def main():
    src = sys.argv[1]
    lines = [
        "// Generated by tool/who_tables.py from the WHO Child Growth Standards; don't edit.",
        "// (age in days, L, M, S) for each indicator and sex, birth to 24 months.",
        "",
        "const whoLms = <String, Map<String, List<(double, double, double, double)>>>{",
    ]
    for name, prefix in INDICATORS.items():
        lines.append(f"  '{name}': {{")
        for sex, key in (("girls", "female"), ("boys", "male")):
            lines.append(f"    '{key}': [")
            for d, l, m, s in rows(src, prefix, sex):
                lines.append(f"      ({float(d)}, {l}, {m}, {s}),")
            lines.append("    ],")
        lines.append("  },")
    lines.append("};")
    out = os.path.join(os.path.dirname(__file__), "..", "lib", "growth", "who_lms.dart")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", os.path.relpath(out))


if __name__ == "__main__":
    main()
